// <auto-generated />
using Domasno_2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Domasno_2.Migrations
{
    [DbContext(typeof(Domasno_2Context))]
    [Migration("20180505125246_TitleCustomer")]
    partial class TitleCustomer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domasno_2.Models.Address", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address1");

                    b.Property<string>("Address2");

                    b.Property<string>("City");

                    b.Property<int?>("CustomerID");

                    b.Property<string>("FirstName")
                        .HasMaxLength(35);

                    b.Property<string>("LastName")
                        .HasMaxLength(15);

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10);

                    b.HasKey("ID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("Domasno_2.Models.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<int>("Age");

                    b.Property<string>("FullName");

                    b.Property<string>("Gender");

                    b.HasKey("ID");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Domasno_2.Models.Publisher", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("StreetAdr");

                    b.Property<int?>("TitleID");

                    b.Property<string>("ZipCode");

                    b.HasKey("ID");

                    b.HasIndex("TitleID");

                    b.ToTable("Publisher");
                });

            modelBuilder.Entity("Domasno_2.Models.Title", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CustomerID");

                    b.Property<DateTime>("PublicationYear");

                    b.Property<string>("TitleName");

                    b.HasKey("ID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Title");
                });

            modelBuilder.Entity("Domasno_2.Models.Address", b =>
                {
                    b.HasOne("Domasno_2.Models.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerID");
                });

            modelBuilder.Entity("Domasno_2.Models.Publisher", b =>
                {
                    b.HasOne("Domasno_2.Models.Title", "Title")
                        .WithMany("Publishers")
                        .HasForeignKey("TitleID");
                });

            modelBuilder.Entity("Domasno_2.Models.Title", b =>
                {
                    b.HasOne("Domasno_2.Models.Customer", "Customer")
                        .WithMany("Titles")
                        .HasForeignKey("CustomerID");
                });
#pragma warning restore 612, 618
        }
    }
}
